docs/docs/lxd_macpine.md
to avoid this 2 message :
- port 22 already assigned on host
- The local image 'ubuntu' couldn't be found, trying 'ubuntu:' instead.
=> Bunam patch 1

Makefile
This is necessary for package managers that do source installation and
install to a location other than /usr/local.
=> Add support for PREFIX and DESTDIR in Makefile

Makefile
Follow up to #38. My goal is to package macpine for Homebrew, and these are the changes I've made to make that possible:
* Create a target for the output binary. This is used as a prerequisite for the
'install' target
* Create an 'install' target to create the target directory and copy the built
executable to that directory
* Do not use 'sudo' when installing the binary (if needed, the user should use
'sudo make install', but not all installations require 'sudo' so it should
not be used in the Makefile directly)
* Consolidate the 'linux' and 'darwin' targets. Go can automatically detect
which OS it is running on and needs to build for. If cross-compilation is
needed, GOOS can be specified when running make:
make GOOS=linux
=> Standardize Makefile for package installation

README.md, cmd/completion.go, docs/docs/completions.md
* Add docs to README
* Make shell list consistent everywhere (bash, fish, zsh, powershell)
* Un-hide completion command in cobra configuration
* Add zsh notes to docs/docs/completions.md and link in README
Closes #68
=> Add documentation for `completion`

cmd/edit.go
* Check for $EDITOR
* If set badly, log errors
* If not set or set badly, default to vim
* If vim missing, default to nano
* Call specified editor as usual
Also fixes a bug where `alpine edit` was checking for `qemu-img` instead of `vim`. Likely an overlooked copypasta.
=> Enable user-selected editor for `alpine edit`

Makefile
* Add `MAIN` and `SRCS` variables to Makefile
* Make the build target depend on `MAIN` and `SRCS`
* Add `clean` target for convenience
Now, if `main.go` or any `.go` file in `cmd/`, `host/`, `qemu/`, or `utils/` changes, `make` will detect that `bin/alpine` is out of date and should be recompiled.
=> Fixes for Makefile behavior

.github/workflows/goscorecard.yml, Makefile, cmd/edit.go
* Run `go fmt` with all flags on `cmd/edit.go`
* Add `Makefile` target `fmt` to conveniently run `gofmt`
* `fmt` target modifies files in-place
* Add a GH Action to auto-refresh the Go Scorecard
=> Go scorecard complained about `cmd/edit.go`

cmd/list.go
* change to `cmd/list.go` to show "-" for PID of Stopped instances
Just a quick vanity change. Example:
Pre-PR:
```sh
$ alpine list
NAME       OS         STATUS      SSH    PORTS ARCH        PID
test       alpine     Stopped     22           aarch64     0
```
Post-PR:
```sh
$ alpine list
NAME       OS         STATUS      SSH    PORTS ARCH        PID
test       alpine     Stopped     22           aarch64     -
```
=> Don't show 0 for PID when VM is stopped

qemu/ops.go
Uses `hwclock -w` during boot up. However, the system clock may be incorrect. If corrected manually or with NTP, `hwclock -w` can be used to also correct the real-timel clock (RTC).
Closes #78 (sort of...)
=> Make RTC sync to system clock

README.md, cmd/completion.go, cmd/delete.go, cmd/exec.go, cmd/import.go, cmd/list.go, cmd/publish.go, cmd/ssh.go, cmd/start.go, go.mod, go.sum, host/exec.go, host/info.go, qemu/ops.go, utils/utils.go
Closes #67, refer to that issue for discussion of changes.
* Bump yaml to v3
* Add optional (`omitempty`) `rootpassword` field to `config.yaml`
* Add optional (variadic) argument to `Exec()` to run as root
* Read `config.yaml` for root password, or use default
* Add comment that `qemu-system-...` creates/deletes the pidfile with
`-pidfile`
* Change retry counters/thresholds to avoid >30 seconds retrying
* Lengthen retry times for i/o operations as they may take longer
* use `Exec("...", true)` to run various mgmt commands as root
* Add `CleanPIDFile` function if `qemu` command succeeds but `Start`
fails
* Add troubleshooting docs in README
=> Fix non-root-ssh issues with `Exec` (and `Start`)

README.md, cmd/delete.go, cmd/exec.go, cmd/import.go, cmd/launch.go, cmd/list.go, cmd/publish.go, cmd/ssh.go, cmd/start.go, go.mod, go.sum, host/info.go, host/launch.go, host/start.go, qemu/ops.go, utils/utils.go
Closes #77.
Now, ports can be specified as `1234` for host-to-VM forwarding (i.e. `host:1234 <-> VM:1234`) or as `2345:3456` (i.e. `host:2345 <-> VM:3456`).
`qemu/ops.go` is updated to create the correct `qemu` rules.
`cmd/launch.go` is updated to validate `-p` argument as either ports or port pairs.
=> Add ':' port mapping configuration option, and briefly document in README

cmd/delete.go, cmd/launch.go, cmd/start.go, qemu/ops.go
A number of internals cleanups and changes to remove the need for `Retry` in `Start` and `Launch`. Calls which were previously handled in `Retry` loops now either block until success, or exit with an error. Therefore, either the function succeeds, or does not need to retry as an error must first be resolved. Closes #79.
Overall summary of edits in `qemu/ops.go`:
* in `Stop()`: simplify and add output
* in `getHostArchitecture()`: fix logging format bug
* changes in `Start()` and `Launch()` (below)
in `Start()`:
* use `-daemonize` and `cmd.Run(..)`
* `cmd.Run(...)` blocks until `qemu-system` succeeds and forks to background
* clarify output (`awaiting ssh`, etc)
* Add PID file cleanup on errors
* Remove unneeded `Retry` calls (calls now block or error rather than
failing silently)
* Mount …
=> Remove `sleep` calls in `Start` and `Launch` processes

host/start.go
If `alpine start` is called on a running VM, `host/start.go` will return an error that the VM is already running -- which `cmd/start.go` interprets as a failure to start the VM, thus annoyingly calling `stop`.
This fixes that.
=> Fix issue in `cmd/start.go`

cmd/delete.go, cmd/edit.go, cmd/exec.go, cmd/launch.go, cmd/list.go, cmd/publish.go, cmd/root.go, cmd/ssh.go, cmd/start.go, cmd/stop.go, cmd/tag.go, host/exec.go, host/info.go, host/status.go, host/stop.go, host/utils.go, qemu/ops.go
Add support for adding and removing, and storing/printing custom string tags on VMs.
=> Tagging vms

cmd/info.go, cmd/list.go, host/info.go
* Change in `cmd/list.go`
* Add `Image` to `alpine info` in case this is needed
* Minor correction in `cmd/info.go` documentation (single instance)
Closes #110
=> Remove OS column from `alpine list`

cmd/restart.go, cmd/root.go, host/start.go
* add `cmd/restart.go`
* accepts multiple instances
* reports errors immediately rather than deferred because output is long during startup
* small simplification in `host/start.go`
* add restart to `cmd/root.go`
Closes #94
=> Add restart command

README.md, cmd/delete.go, cmd/edit.go, cmd/exec.go, cmd/import.go, cmd/info.go, cmd/launch.go, cmd/list.go, cmd/publish.go, cmd/rename.go, cmd/restart.go, cmd/root.go, cmd/ssh.go, cmd/start.go, cmd/stop.go, cmd/tag.go, host/utils.go, utils/utils.go
Tags will now be expanded for commands with multiple instance support:
* `cmd/delete.go`
* `cmd/edit.go`
* `cmd/publish.go`
* `cmd/restart.go`
* `cmd/start.go`
* `cmd/stop.go`
Format is: `alpine start +tagname`
For example:
```bash
$ alpine list
NAME       STATUS      SSH    PORTS     ARCH        PID   TAGS
mysql      Stopped     2022   3306      aarch64     -     daemon
foobar     Stopped     2023             aarch64     -     daemon,dev
$ alpine start +daemon
... starts mysql and foobar ...
$ alpine stop mysql +dev
... stops mysql and foobar ...
```
=> Tagging vms for efficient multi-instance commands

cmd/publish.go, utils/utils.go
This addresses #136 
The pull request also makes a switch to pause/resume rather than stop/start as that is considerably faster.
The VM is auto started only if it had been running prior to publish.
It is desirable for the VM to be stopped for publish,, but is not essential. A stopped VM will contain a fixed state (if there were any write operations running). For safety, it may be desirable, to prevent the user from publishing a Running VM and force the user to manually stop/pause it to ensure the user remains in control of the final publishable VM step.
Can have a discussion about this and incorporate into this PR if desirable.
=> auotstart an instance on publish if it was already running

README.md, qemu/ops.go
This adds AVX/AVX2 instruction support to x86 emulation. This feature should be able to enable installation of tools such as tensorflow inside containers running on top of macpine VMs
=> Avx support

qemu/ops.go
This fixes errors when vm artefacts are not deleted on sigterm
=> remove pid, sock, and qmp files on stop

utils/utils.go
=> Check for bad filenames in tar archive expansion in utils/utils.go
